### ISSUE TITLE
Usage with gulp

### ISSUE THREAD

**Issue by bhargavrpatel** [jlongster/prettier#206]
Hello,

It seems I am not able to successfully pipe a source into prettier. Here is a sample snippet...

```js
gulp.task('default', () => {
  gulp.src("./main.js")
  .pipe(prettier.format(formatSettings))
  .pipe(gulp.dest('dist'))
  .pipe(notify("Hello Gulp!"));
});
````

and the error I see...

```
[15:16:20] Using gulpfile ~/workspace/ireader/gulpfile.js
[15:16:20] Starting 'default'...
[15:16:20] 'default' errored after 12 ms
[15:16:20] TypeError: text.startsWith is not a function
    at formatWithShebang (/Users/bhargavpatel/workspace/ireader/node_modules/prettier/index.js:57:13)
    at Object.format (/Users/bhargavpatel/workspace/ireader/node_modules/prettier/index.js:69:12)
    at Gulp.gulp.task (/Users/bhargavpatel/workspace/ireader/gulpfile.js:41:18)
    at module.exports (/Users/bhargavpatel/workspace/ireader/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/bhargavpatel/workspace/ireader/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/bhargavpatel/workspace/ireader/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/bhargavpatel/workspace/ireader/node_modules/orchestrator/index.js:134:8)
    at /Users/bhargavpatel/.nvm/versions/node/v6.9.1/lib/node_modules/gulp/bin/gulp.js:129:20
```

**Comment by vjeux** [comment]
Looks like it breaks because `startsWith` is not defined. Can you tell us what version of node you are using?

**Comment by mikaelbr** [comment]
@bhargavrpatel You can't simply pipe gulp things into arbitrary functions. `gulp.src("./main.js")` creates a Node stream of [vinyl files](https://github.com/gulpjs/vinyl). This is why you get an error with `text.startsWith`, because you don't pass text to the function `prettier.format`. Vinyl files in turn has a property with file contents (new stream) which can be used.

To do this, you'd have to make a write stream which takes contents of all piped vinyl files, transform them using `prettier` and writes to a returning stream with the transformed content. You can use something like [through2-map](https://www.npmjs.com/package/through2-map) (or similar) to do this.

Look at how you create gulp plugins to get a better understanding of how this works: https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/README.md

This is a good use case where you can create a new project: `gulp-prettier`

**Comment by bhargavrpatel** [comment]
Thanks @mikaelbr I realized this after the post, not sure why this only supports text input at the moment though. Makes things very hard!

**Comment by mikaelbr** [comment]
I think supporting only text in this makes the most sense, to be honest. It's always easier to go to higer abstractions such as streams, promises, buffers (etc) as external code, but it's not practical (or smart, IMO) to try to support all different types of consuming.

It should be fairly trivial, and little effort, to make this work with gulp and streams, exactly due to it operating on a "primitive" data type (text). Even if the project could operate on streams (which would make it not work in the browser), it wouldn't work in gulp, as it uses it's own abstraction (vinyl files).

**Comment by bhargavrpatel** [comment]
Makes sense. Thanks! Let me read up on gulp plugin creation and perhaps I can contribute. Will report any success, if any.

**Comment by mikaelbr** [comment]
There are many examples out there which wraps APIs just like this which you can get some inspiration from. For instance: https://github.com/sindresorhus/gulp-markdown/blob/master/index.js

**Comment by bhargavrpatel** [comment]
Closing issue, I finished it. Thanks for the reference repository. I opted to look at gulp-coffee which does a bit of extra stuff like allowing for options etc.

**Comment by bhargavrpatel** [comment]
@mikaelbr Suggestions on how I should go about writing tests for the prettier gulp plugin? Should I just test itself or should all of the underlaying tests pass too?
