### ISSUE TITLE
[MemberExpression] Long object access doesn't wrap

### ISSUE THREAD

**Issue by JakeCoxon** [jlongster/prettier#21]
Not sure if this is a bug or just a rare enough case that it doesn't matter

Input
```
something()
  .something
  .something()
  .something
  .something()
  .something
  .something()
```

Output
```
something().something.something().something.something().something.something();
```
(Longer than 60 chars)

Input
```
someVeryLongMethodObjectName
  .withSomeVeryLongObjectKey
  .andAnotherLongKey;
```

Output
```
someVeryLongMethodObjectName.withSomeVeryLongObjectKey.andAnotherLongKey;
```

**Comment by vjeux** [comment]
Repro case

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22someVeryLongMethodObjectName%5Cn%20%20.withSomeVeryLongObjectKey%5Cn%20%20.withSomeVeryLongObjectKey%5Cn%20%20.andAnotherLongKey%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Afalse%7D%7D

**Comment by despairblue** [comment]
@JakeCoxon If you want to give it a shot you might be interested in the discussion in #212 and my take on this (which created a lot of other issues) in #217.

I'd still like to see a solution for this. Chai assertions are another thing that suffer from this. 

I wonder if there is a way to only add an softspace after a dot if the currently printed line would exceed the max line length with the next token. But I think that's not easy at all and not performant.

**Comment by vjeux** [comment]
@despairblue do you mind giving a real-world example of chai assertions that do not look good? It's usually better for this kind of things to look at real code rather than make up examples.

**Comment by despairblue** [comment]
@vjeux sure [this](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22expect(email.sendToLandlordBookingCreated.calledOnce)%5Cn%20%20.to.equal(true)%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A60%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Afalse%2C%22doc%22%3Afalse%7D%7D) would be a small one. I'd rather see the left case instead of the right one.

Or [this one](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22if%20(testConfig.ENABLE_ONLINE_TESTS%20%3D%3D%3D%20'true')%20%7B%5Cn%20%20describe('POST%20%2Fusers%2Fme%2Fpet'%2C%20function%20()%20%7B%5Cn%20%20%20%20it('saves%20pet'%2C%20function%20()%20%7B%5Cn%20%20%20%20%20%20function%20assert%20(pe)%20%7B%5Cn%20%20%20%20%20%20%20%20expect(bankAccount)%5Cn%20%20%20%20%20%20%20%20%20%20.to.have.property('OwnerAddress')%5Cn%20%20%20%20%20%20%20%20%20%20.that.deep.equals(%7B%20%5Cn%20%20%20%20%20%20%20%20%20%20%5CtAddressLine1%3A%20'Alexanderstrasse'%2C%20%5Cn%20%20%20%20%20%20%20%20%20%20%5CtAddressLine2%3A%20''%2C%20%5Cn%20%20%20%20%20%20%20%20%20%20%5CtPostalCode%3A%20'10999'%2C%20%5Cn%20%20%20%20%20%20%20%20%20%20%5CtRegion%3A%20'Berlin'%2C%20%5Cn%20%20%20%20%20%20%20%20%20%20%5CtCity%3A%20'Berlin'%2C%20%5Cn%20%20%20%20%20%20%20%20%20%20%5CtCountry%3A%20'DE'%20%5Cn%20%20%20%20%20%20%20%20%20%20%7D)%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D)%5Cn%20%20%7D)%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Afalse%2C%22doc%22%3Afalse%7D%7D) which is a little longer.

**Comment by vjeux** [comment]
@despairblue thank you! This is great! Shouldn't be too hard to make work.

**Comment by vjeux** [comment]
With #462 it looks like

```js
if (testConfig.ENABLE_ONLINE_TESTS === "true") {
  describe("POST /users/me/pet", function() {
    it("saves pet", function() {
      function assert(pet) {
        expect(pet).to.have.property("OwnerAddress").that.deep.equals({
          AddressLine1: "Alexanderstrasse",
          AddressLine2: "",
          PostalCode: "10999",
          Region: "Berlin",
          City: "Berlin",
          Country: "DE"
        });
      }
    });
  });
}
```

which is better. But we should also be able to break the `.to.have.property()`
