### ISSUE TITLE
[MemberExpression] Chained values with following function calls don't get split into lines

### ISSUE THREAD

**Issue by arnarthor** [jlongster/prettier#212]
When taking a look at a reproduction of https://github.com/jlongster/prettier/issues/200 I noticed that if some really long chain of nested objects occurred and then a following function call, it does not split the nesting into new lines.

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22request.hello.world.function('foo').some.really.really.really.really.really.really.really.really.really.really.really.really.really.really.really.really.really.really.really.long.constant.post('%2Fversion')%20%20%2F%2F%20comment%201%5Cn%20%20.set('Prefer'%2C%20'plurality%3Dsingular')%20%2F*%20comment%202%20*%2F%5Cn%20%20.send()%5Cn%20%20%5Cnrequest%5Cn%20%20.post.version%20%20%2F%2F%20comment%201%5Cn%20%20.set.Prefer.plurality.singular%20%2F*%20comment%202%20*%2F%5Cn%20%20.send()%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A40%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Afalse%7D%7D

I would love to work on this issue myself, but it might take me some time to wrap my head around the code if it's alright that the fix won't be ready within a day or two 😄

**Comment by vjeux** [comment]
You should try to fix it, the code that's responsible for it is https://github.com/jlongster/prettier/blob/d8c51483fc3c27233c40e99953487ef31966b38e/src/printer.js#L1985

Can't guarantee no one will try and fix it in parallel as there are quite a few issues raised about this part of the code, but worst case, you may have learned something :)

**Comment by jlongster** [comment]
Yeah, this is a great part of the code to dive into if you're up for a challenge! I really need to write better documentation than [commands.md](https://github.com/jlongster/prettier/blob/master/commands.md) but that's all we have for now.

The main reason is because we don't break on property accesses. The only time we do is when we think you are trying to use promise/observables/or some library that does a lot of function chaining:

```js
observable
  .map(x => { ... })
  .switchWhat(x => { ...})
```

That's a really common pattern in JS and that syntax is desirable.

But for generic property accesses like `foo.bar.bar` you don't want to break. At least, usually you don't. I don't think it's usually a problem that we don't break on generic property accesses. When you're looking up a deeply nested object, you usually want `foo.bar.prop("baz").biz` to stay as one thing just like a variable would.

Where should it break? Should it split the entire lookup across lines (one lookup per line?) or be more like binary expressions where we try to fit as many as we can on one line? The former is too aggressive imho for simple lookups and the latter technically complicated.

Before you spend a ton of time on this, I just want to make sure you are hitting this on real code and it's not just an abstract use case. If you want to to play around with the code and show us various formats we can output with this case, by all means do! But note that if it introduces a lot of complexity, we'll probably only merge it if it solves a pattern people use in the real-world.

**Comment by despairblue** [comment]
I tried to fix this as well. I added a conditional group for the member lookup, so it breaks if necessary. Though I'm not sure this is the best idea. I'll open a PR today.

**Comment by despairblue** [comment]
@jlongster the real code that I'm trying to fix is [this](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20*%20sendMail%20()%20%7B%5Cn%20%20try%20%7B%5Cn%20%20%20%20const%20pdfStream%20%3D%20yield%20contractsService%5Cn%20%20%20%20%5Ct.getLandlordContractStreamFromBooking(booking)%5Cn%20%20%7D%20catch%20(error)%20%7B%5Cn%20%20%20%20report(error)%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D).

I also thought about breaking after the assignment operator, which I generally prefer, but I know that's unconventional (writing Elm, one gets used to this):

```js
function* sendMail() {
  try {
    const pdfStream =
      yield contractsService.getLandlordContractStreamFromBooking(booking);
  } catch (error) {
    report(error);
  }
}```

I opted for breaking after the member lookup instead:

```js
function* sendMail() {
  try {
    const pdfStream = yield contractsService
      .getLandlordContractStreamFromBooking(booking);
  } catch (error) {
    report(error);
  }
}
```

@arnarthor yours would be formatted as:

```js
request.hello.world.function("foo").some
  .really.really.really.really.really
  .really.really.really.really.really
  .really.really.really.really.really
  .really.really.really.really.long
  .constant
  .post("/version")
  .set("Prefer", "plurality=singular")
  .send();

// comment 1
request.post.version.set.Prefer
  .plurality.singular /* comment 2 */
  .send();
```

This allows for newlines after a member lookup if really necessary to adhere to the max-width.
