### ISSUE TITLE
Newline after "use strict" on babylon

### ISSUE THREAD

**Issue by erbridge** [jlongster/prettier#216]
This may be one of those personal taste issues, but I prefer to leave a newline between the `"use strict"` statement and any imports. It seems to create the same rhythm as leaving newlines between function definitions and import groups (I group by system, vendor, internal).

**Comment by erbridge** [comment]
Note that prettier is actually stripping the newline in this case. Perhaps it could just leave it alone, like it does for other newlines?

**Comment by vjeux** [comment]
Thanks for the report, this is indeed a bug and should be fixed!

Repro case

```js
./bin/prettier.js test.js
/* @flow */
"use strict";
import a from "a";

vjeux();
```

```js
./bin/prettier.js test.js --flow-parser
/* @flow */

"use strict";

import a from "a";

vjeux();
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%2F*%20%40flow%20*%2F%5Cn%5Cn'use%20strict'%3B%5Cn%5Cnimport%20a%20from%20'a'%3B%5Cn%5Cnvjeux()%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

It works fine on the flow parser but not on babylon. The reason is that babylon has a separate `directives` field for `'use strict';` instead of being part of the normal ast.
