### ISSUE TITLE
Import/Export format objects missing space before comma

### ISSUE THREAD

**Issue by arnarthor** [jlongster/prettier#255]
```js
export {runTaskForChanged as task,description};
```

I expected this to format this as follows 
```js
export {runTaskForChanged as task, description};
```

with bracket spacing off

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22export%20%7BrunTaskForChanged%20as%20task%2C%20description%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
It should probably be formatted as

```js
export {
  runTaskForChanged as task,
  description,
};
```

**Comment by vjeux** [comment]
Thanks for all those issues, keep them coming!

**Comment by vjeux** [comment]
I can't reproduce neither on 0.0.7 nor on master.

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22export%20%7BrunTaskForChanged%20as%20task%2Cdescription%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

Can you try to upgrade to the latest version and see if it works? Otherwise, provide an example that doesn't on the web version of prettier? Thanks!

**Comment by arnarthor** [comment]
https://jlongster.github.io/prettier/#%7B%22content%22%3A%22export%20%7BrunTaskForChanged%20as%20task%2C%20description%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Afalse%7D%7D

Turn off bracket spacing 👍
