### ISSUE TITLE
JSX exeeds line length limit

### ISSUE THREAD

**Issue by dmnd** [jlongster/prettier#26]
Expected:

```js
function Component() {
  return (
    <div 
      id="longid" 
      className="longclassname"
      foo="longvalue" 
      bar="longvalue"
      baz="longvalue"
    >
      hello
    </div>
  );
}
```

Actual
```js
function Component() {
  return (
    <div id="longid" className="longclassname" foo="longvalue" bar="longvalue" baz="longvalue">
      hello
    </div>
  );
}
```

**Comment by jlongster** [comment]
Yeah, JSX needs a few more tweaks before it's totally viable.

**Comment by joshwcomeau** [comment]
It looks like JSX currently breaks around any non-string attributes:

```js
<Thing stringProp="thing" objectProp={
  object.property
} otherStringProp="hi there">
```

I think the emphasis should be on keeping props grouped, but splitting on the space between props. Of course it's tricky, because sometimes you'll want to do both:

```js
<Thing
  stringProp="yeah"
  objectProp={{
    hi: 5,
  }}
>
```

I believe this is the most widely-used approach for spacing JSX, as specified in [AirBnb's JS guide](https://github.com/airbnb/javascript/tree/master/react#alignment).

Thanks for your work on this project, you're attempting to solve a problem that has been a thorn in my side for years :)

**Comment by vramana** [comment]
Closing this in favour of #73
