### ISSUE TITLE
JSX ternary is strange

### ISSUE THREAD

**Issue by arnarthor** [jlongster/prettier#317]
```diff
-            {__DEV__ ? this.renderDevApp() : (
-              <div>
-                {routes.map((route) =>
-                  <MatchAsync
-                    key={`${route.to}-async`}
-                    pattern={route.to}
-                    exactly={route.to === '/'}
-                    getComponent={routeES6Modules[route.value]}
-                  />,
-                )}
-              </div>
-            )}
+            {__DEV__ ? this.renderDevApp() : <div>
+                  {
+                    routes.map(route => (
+                      <MatchAsync
+                        key={`${route.to}-async`}
+                        pattern={route.to}
+                        exactly={route.to === '/'}
+                        getComponent={routeES6Modules[route.value]}
+                      />
+                    ))
+                  }
+                </div>}
```

Just ran prettier on the codebase at work after your 0.0.9 release and this is a really strange diff.

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22class%20App%20extends%20PureComponent%20%7B%5Cn%20%20props%3A%20Props%3B%5Cn%5Cn%20%20render()%20%7B%5Cn%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%3Cdiv%20className%3D%7Bstyles.container%7D%3E%5Cn%20%20%20%20%20%20%20%20%3Cdiv%20className%3D%7Bstyles.content%7D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3CHeader%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%7B__DEV__%20%3F%20this.renderDevApp()%20%3A%20(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7Broutes.map((route)%20%3D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CMatchAsync%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20key%3D%7B%60%24%7Broute.to%7D-async%60%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20pattern%3D%7Broute.to%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20exactly%3D%7Broute.to%20%3D%3D%3D%20'%2F'%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20getComponent%3D%7BrouteES6Modules%5Broute.value%5D%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%3E%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20)%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20%20%20%20%20%20%20)%7D%5Cn%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20)%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
cc @rattrayalex

**Comment by rattrayalex** [comment]
Hmm... that's "funny" because I had actually special-cased ternaries not to wrap jsx in parens...

@arnarthor what would you think of this output:

```jsx
{__DEV__ ? this.renderDevApp() : 
  <div>
    {
      routes.map(route => (
        <MatchAsync
          key={`${route.to}-async`}
          pattern={route.to}
          exactly={route.to === '/'}
          getComponent={routeES6Modules[route.value]}
        />
      ))
    }
  </div>
}
```
or
```jsx
{__DEV__ 
  ? this.renderDevApp() 
  : <div>
      {
        routes.map(route => (
          <MatchAsync
            key={`${route.to}-async`}
            pattern={route.to}
            exactly={route.to === '/'}
            getComponent={routeES6Modules[route.value]}
          />
        ))
      }
    </div>
}
```

ternaries generally are pretty strange and definitely need some work/thought IMO (unless they've received some lately). I had been planning to tackle ternaries (esp w/r/t jsx) next week if nobody else had picked it up.

In this case, I actually like the original formatting with parens, though many other cases look bad with parens. For example, this is something I've seen and not hated:

```jsx
{ __DEV__ 
  ? <MatchAsync
      key={`${route.to}-async`}
      pattern={route.to}
      exactly={route.to === '/'}
      getComponent={routeES6Modules[route.value]}
    />
  : <div>
      <MatchAsync
        key={`${route.to}-async`}
        pattern={route.to}
        exactly={route.to === '/'}
        getComponent={routeES6Modules[route.value]}
      />
    </div>
}
```
and using parens instead is questionable... could be... 
```jsx
{__DEV__ ? (
  <MatchAsync
      key={`${route.to}-async`}
      pattern={route.to}
      exactly={route.to === '/'}
      getComponent={routeES6Modules[route.value]}
    />
) : (
  <div>
    <MatchAsync
      key={`${route.to}-async`}
      pattern={route.to}
      exactly={route.to === '/'}
      getComponent={routeES6Modules[route.value]}
    />
  </div>
)}
```
but I'm pretty sure that was suggested before to the revulsion of onlookers. 

It might also be worth special-casing `null` cases, such as:
```jsx
{hideTheThing ? null : 
  <div>
    the thing is shown
  </div>
}
```
and
```jsx
{showTheThing ?
  <div>
    the thing is shown
  </div>
: null}
```
The sad thing about ternaries is that there isn't really any good answer, they're inherently ugly. Personally I feel they're the worst part of JSX, since the combination of a jsx {expression}, a ternary, and a multiline jsx component is often needed and never nice.

Anyway, we should have a broader discussion on this... What would be the right thread for that?

**Comment by rattrayalex** [comment]
plus, of course, you have to keep in mind what to do when ternaries are used in an if-else chain...

**Comment by arnarthor** [comment]
I feel like this one
```js
{__DEV__ ? this.renderDevApp() : 
  <div>
    {
      routes.map(route => (
        <MatchAsync
          key={`${route.to}-async`}
          pattern={route.to}
          exactly={route.to === '/'}
          getComponent={routeES6Modules[route.value]}
        />
      ))
    }
  </div>
}
```

Looks pretty nice. I also like the one where the elements are wrapped in parens, like the one that got formatted out in my original diff.

I've been running this on a pretty big React app now since day 1 and it's definitely gotten better, but I still feel there's some work left for JSX. 

If you're interested in a sort of pairing session on this during a weekend or something like that I would love to help out. It's pretty hard since I live in Iceland so time coordination could be an issue on that, but if we could do some async discussion on gitter I would really love to help you out with this.

I've been fighting an uphill battle on this at work, people love the idea, but have they still have too strong opinions on code formatting to accept everything that prettier suggests. The sooner it get's really good at these cases the better 😄

**Comment by rattrayalex** [comment]
Awesome! 

@jlongster what's the best way to gather input on what makes for a pretty (jsx) ternary?

In case it's helpful, I added a number of test case examples [here](https://github.com/jlongster/prettier/blob/master/tests/prettier/jsx-stateless-arrow-fn.js#L58), largely as a TODO

**Comment by jlongster** [comment]
@rattrayalex Not sure, @vjeux gives great feedback because he runs it on large codebases and sees what changes. I think here in the issues is fine place to talk about stuff; a decent number of people are watching the repo so they can chime in if they want.

I don't think ternaries should be changed, honestly. The output in in your tests looks good except for an indentation issue. We will never be able get the format exactly how everybody expects in every case. There are far too many exceptions with how people want things. Usually if someone wants something formatted a specific way, they don't realize that that impacts a bunch of other cases with the same form when combined with other things.

This formatter enforces consistency. We hold that above all else, include a programmer's preference for a specific situation. Once everything is so consistent, you get used it and it doesn't look weird anymore.

That's not to say we haven't gone out of our way a lot to make specific patterns look pretty. There may be something we can do here, but maybe not.

Ternaries always break so that they align like this:

```
var x = foo
  ? truthfulCase
  : falseyCase;
```

We can work on improving that. Maybe all we need to do is allow the `falseyCase` to break down first and the `truthfulCase` can stay on the same line if possible. Otherwise, it breaks like the above.

**Comment by jlongster** [comment]
I meant to say this: I don't see how JSX should have special treatment of ternaries at all. Specializing the different operators in different contexts defeats the purpose of this formatter which is to have predictable formatting. JSX is just another value, just like big objects, etc. They should all break the same way.

**Comment by arnarthor** [comment]
I agree that consistency is key. Having all ternaries the same should definitely be the end goal. 

In my original diff it's strange though both due to the indent being to big and the closing braces after the closing div is in the wrong place as well. 

If we're thinking of consistency for this, my vote would be this
```js
{__DEV__ 
  ? this.renderDevApp() 
  : <div>
      {
        routes.map(route => (
          <MatchAsync
            key={`${route.to}-async`}
            pattern={route.to}
            exactly={route.to === '/'}
            getComponent={routeES6Modules[route.value]}
          />
        ))
      }
    </div>
}
```

Since this is the format that I've noticed ternaries in non-jsx code have.

**Comment by rattrayalex** [comment]
Awesome, thanks for the clarity! 

I didn't know ternaries were already consistent in their formatting – and if the output that @arnarthor highlighted is acceptable everyone (at time of writing, it has three 👍 and zero 👎 , so I assume it is), then the fix should be as simple as: 

1. fix the indentation of the JSX
2. Don't add a newline+indent after opening `{` in JSX Expressions, at least in this case (might be hard if some need indentation and others don't).

**Comment by zachlysobey** [comment]
(disclaimer: I haven't yet dug too deeply into this project)

Not sure where the right place to bring this up is or if its already been discussed, but one thing I like about tools like eslint is that I do things like make a rule that disallows multi-line ternaries.

With prettier (and please correct me if I'm wrong), what I get is consistent formatting of the multi-line ternary, but no way disallow them or "fix" them into if/else's?

I guess I could use a small set of eslint rules and run them in combination with prettier to get everything I want?

Is this project's purpose to totally replace eslint, or do you think there is room for both?

**Comment by vjeux** [comment]
@zachlysobey the goal of `prettier` is to format the existing AST but not modify it. This is out of scope to replace ternaries into if/then/else.

In practice, we are doing a few tiny exceptions like removing spurious `;` which are `EmptyExpression`.

**Comment by rattrayalex** [comment]
https://github.com/jlongster/prettier/pull/473 fixes part of this, but not all; 

```jsx
    {props.showTheThing
      ? <BaseForm
        url=\"/auth/google\"
        method=\"GET\"
        colour=\"blue\"
        size=\"large\"
        submitLabel=\"Sign in with Google\"
      >
        Hello world
      </BaseForm>
      : \"hello \" + \"howdy! \"}
```

should instead be:

```jsx
{props.showTheThing
  ? <BaseForm
      url=\"/auth/google\"
      method=\"GET\"
      colour=\"blue\"
      size=\"large\"
      submitLabel=\"Sign in with Google\"
    >
      Hello world
    </BaseForm>
  : \"hello \" + \"howdy! \"}
```

I'm planning to try to tackle that issue now.
