### ISSUE TITLE
#!/usr/bin/env node gets translated to ///usr/bin/env node

### ISSUE THREAD

**Issue by rtorr** [jlongster/prettier#341]
`#!/usr/bin/env` node gets translated to `///usr/bin/env node`

expected behavior would be to not change `#!/usr/bin/env `

version: `0.0.9`
OS: OSX
editor tool: prettier-vscode

**Comment by hawkrives** [comment]
That should have been fixed with https://github.com/jlongster/prettier/issues/137, which is part of both v0.0.8 and v0.0.9…

It also works on the [online version](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22%23!%2Fusr%2Fbin%2Fenv%20node%5Cnconsole.log('blah')%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D). 

It's odd that `prettier-vscode` would have a different behavior. I'll take a peek at that in a bit.

**Comment by hawkrives** [comment]
It appears that `prettier-vscode` is still on prettier@v0.0.7 (see the [package.json](https://github.com/esbenp/prettier-vscode/blob/master/package.json#L95)), but https://github.com/esbenp/prettier-vscode/pull/22 was opened about two hours ago and should update the dependency.

Hopefully that fixes it!

**Comment by rtorr** [comment]
@hawkrives thanks for checking! That must be it. thanks
