### ISSUE TITLE
Adding extra line from vim

### ISSUE THREAD

**Issue by RileyTomasek** [jlongster/prettier#377]
I'm not sure how to determine if this is caused by vim or prettier, so sorry in advance if it is caused by vim.

After installing prettier globally and adding `autocmd FileType javascript set formatprg=prettier\ --stdin` to my .vimrc, I am seeing the following.

Initial state:
```js
function test() {
  return 'hello';
}
```

Action:
Type `gggqG`, which selects the whole file and runs prettier on it. Unfortunately, the formatting part works, but I am left with an extra newline at the end of the file. The same thing happens if you go in visual mode, select the whole file and type `gq`.

Let me know if there is any other info that would be helpful or if there is any way I can help. Thank you so much for your work, I have been loving prettier so far!

**Comment by kmcq** [comment]
Me too. I don't know that much about `gq` to think of why this may be happening, but my temporary workaround is this:

```vim
autocmd FileType javascript nnoremap gq gqdd
autocmd FileType javascript vnoremap gq gqdd
```

**Comment by demoneaux** [comment]
Prettier adds a newline to the end of each file, so this is working as unexpected, unless you mean that there are two newlines at the end of the file?

**Comment by kmcq** [comment]
It's not necessarily at the end of a file, but I think that's because prettier assumes what it receives in stdin is a "file". Anyway, here are some screenshots:

Before prettier
<img width="1296" alt="screen shot 2017-01-23 at 8 52 52 am" src="https://cloud.githubusercontent.com/assets/3272924/22206509/9b86daa4-e149-11e6-924f-b52005726789.png">

After prettier in vim
<img width="302" alt="screen shot 2017-01-23 at 8 53 32 am" src="https://cloud.githubusercontent.com/assets/3272924/22206512/a18d6f30-e149-11e6-944a-a950d7e3f014.png">

After prettier in command line (I undid the vim changes first)
<img width="277" alt="screen shot 2017-01-23 at 8 54 25 am" src="https://cloud.githubusercontent.com/assets/3272924/22206525/ace7b20a-e149-11e6-8f91-4b9a60ec41d1.png">

**Comment by lydell** [comment]
This happens because `console.log()` adds yet a newline at the end of file. This is not specific to vim. PR coming soon.

**Comment by kmcq** [comment]
Thanks @lydell!
