### ISSUE TITLE
Should short nested objects be inline?

### ISSUE THREAD

**Issue by Haroenv** [jlongster/prettier#43]
Currently any object which isn't really long is written inline. However I usually prefer if an object has been written "vertically" that the nested objects would be written "vertically" too. What's your opinion on this?

Here's an example of what I mean, personally I think the previous version makes more sense, but I'd love to be *enlightened*

```diff
const options = {
       find: '',
       placeholder: undefined,
       mark: false,
-      class: {
-        visible: undefined,
-        hidden: 'hidden'
-      },
+      class: { visible: undefined, hidden: 'hidden' },
       dynamic: false,
       minCharacters: 0,
       hiddenAttr: false
}
```

**Comment by p8952** [comment]
This would be really useful, another example of this being unintuitive is with `module.exports`. With `--print-width` set to 80 it generally works as long as you don't have tiny function names, but with a larger width it puts them all onto one line.

```
$ ./node_modules/.bin/prettier form.js

module.exports = {
  createForm: createForm,
  listForm: listForm,
  retrieveForm: retrieveForm,
  updateForm: updateForm,
  deleteForm: deleteForm
};
```

```
$ ./node_modules/.bin/prettier --print-width 180 form.js

module.exports = { createForm: createForm, listForm: listForm, retrieveForm: retrieveForm, updateForm: updateForm, deleteForm: deleteForm };
```

**Comment by jlongster** [comment]
That's sort of the point of the formatter. It will fit code where it can. The printer will forcibly break a lot of constructs because that's how they look bests, but objects are going to collapse like that.

There are many other times where a short objects is what you want, and this is the kind of styling that I think we need to be less opinionated about. If you add more it's not more work to break it vertically when needed because the formatter will do it for you.

**Comment by Haroenv** [comment]
Sure, I assumed that would be the case, but just wanted to let you know that it could be a "fixable" issue, although it's mostly just a can of worms

Thanks for your work 😄
