### ISSUE TITLE
cases in switch statements not indented

### ISSUE THREAD

**Issue by michaelficarra** [jlongster/prettier#56]
prettier is printing cases at the same indentation level as their parent switch statement. I indent cases inside a switch statement.

Now:

```js
switch (something) {
case "foo":
  // ...
  break;
case "bar":
  // ...
  break;
}
```

Ideally:

```js
switch (something) {
  case "foo":
    // ...
    break;
  case "bar":
    // ...
    break;
}
```

**Comment by bakkot** [comment]
Note that this produces

```js
switch (something) {
  case "foo": {
      iAmIndentedTwice;
    }
}
```

**Comment by gre** [comment]
I was about to raise a bug that `case` have an extra indenting level and found that this issue is actually producing this "bug" :smile:

Is there an available option to get back to the `switch` to be aligned with `case` ?
I'm used to this convention and I thought it was standard? ESlint complaints that the `switch` is supposed to be aligned with `case`. 

There is a whole debate on internet about this, so I guess it should made an option?

**Comment by mrspeaker** [comment]
Yeah, this is annoying (but still, worth it - 'cause Prettier is excellent) - I have to run Prettier, then go re-un-indent the case statement, then save the file. 

Seeing as the original Prettify behavior was "correct" then "fixed" in a PR because of someone's personal preference - it feels like this should be an option.

**Comment by azz** [comment]
My opinion is that due to `case` ending in a `:`, it should be treated the same as a label, and not indented.

**Comment by bakkot** [comment]
You can configure eslint to match prettier.

---

I strongly suspect the style prettier currently produces is by far the more common, and that most people will not refuse to use prettier because it enforces this style (although of course some people will). It is, for example, the style recommended by [AirBnB](https://github.com/airbnb/javascript/blob/b87cb5cdad74199d3fcb83d135e466c29a56ff4e/packages/eslint-config-airbnb-base/rules/style.js#L80), [Google](https://google.github.io/styleguide/jsguide.html#formatting-switch-statements), and [standard-js](https://github.com/feross/eslint-config-standard/blob/bff0a4bb3447b90fc65a2de57be5d123842f6f69/eslintrc.json#L52). As such, this seems like a textbook case where prettier should [resist adding configuration](https://github.com/prettier/prettier/issues/40). Remember, prettier is supposed to be opinionated!

Try this style; I bet you'll get used to it quick.

**Comment by mrspeaker** [comment]
I can get used to ANY style quickly - but personally ESLint is the my standard and I have to make my tools work around it. I agree it doesn't have to be an option but it should be opinionated that case statements are labels and shouldn't be indented, just as the original author made it. I think it should be changed back, people will get used to the non-indented style quickly.

Though really it's just patching Prettier every release, which is easy enough.

**Comment by dvlsg** [comment]
Just some additional insight into why it may be helpful to indent case statements:

```js
// without braces for case
const val = 'bar';
switch (val) {
case 'foo':
  const b = 'bar';
  break;
case 'bar':
  const b = 'baz'; // SyntaxError: Identifier 'b' has already been declared
  console.log(b);
  break;
} // looks okay
```

```js
// with braces for each case, no indentation
const val = 'bar';
switch (val) {
case 'foo': {
  const b = 'bar';
  break;
}
case 'bar': {
  const b = 'baz'; // works!
  console.log(b);
  break;
}
} // two braces in a row at the same indent looks odd
```

```js
// with braces for each case, with indentation
const val = 'bar';
switch (val) {
  case 'foo': {
    const b = 'bar';
    break;
  }
  case 'bar': {
    const b = 'baz'; // works!
    console.log(b);
    break;
  }
} // looks "normal" to me
```
