### ISSUE TITLE
Extra newline when wrapped (call or object or array) expression is in a binary expression

### ISSUE THREAD

**Issue by amasad** [jlongster/prettier#583]
```js
foooooooooooooooooooooooooooooooooooooooooooooooooooooooooo(aaaaaaaaaaaaaaaaaaa) + a;
```

prints:

```
foooooooooooooooooooooooooooooooooooooooooooooooooooooooooo(
  aaaaaaaaaaaaaaaaaaa
) +
  a;
```

**Comment by vjeux** [comment]
There's another similar issue with === -1 where -1 is on its own line.

It's unclear how this should be fixed.

By the way, could you post some real code that triggers this behavior (feel free to change sensitive names) so that we can have concrete examples to talk about. Those made up repro cases aren't great for discussing about how to change the algorithm, thanks!
