### ISSUE TITLE
How different from esprima + escodegen

### ISSUE THREAD

**Issue by ariutta** [jlongster/prettier#630]
I searched the issues for any discussion of how this relates to the combination of [esprima](http://esprima.org/) and [escodegen](https://github.com/estools/escodegen). In case anyone else is searching for the same thing, one difference is handling of line length, as discussed in the README:

### sample input
```js
foo(reallyLongArg(), omgSoManyParameters(), IShouldRefactorThis(), isThereSeriouslyAnotherOne());
```

### escodegen output
```js
foo(reallyLongArg(), omgSoManyParameters(), IShouldRefactorThis(), isThereSeriouslyAnotherOne());
```

### prettier output
```js
foo(
  reallyLongArg(),
  omgSoManyParameters(),
  IShouldRefactorThis(),
  isThereSeriouslyAnotherOne()
);
```

**Comment by wmhilton** [comment]
I'm searching the same thing. Is line length the ONLY difference? Also, what *happened* to [`escodegen`](https://github.com/estools/escodegen)? It has like 4 commits in the past *year*. And how does this project compare with say, [`babel-generator`](https://github.com/babel/babel/tree/7.0/packages/babel-generator) which appears to be quite active? All the discussion on the README focuses on comparing `prettier` to `eslint` instead of comparing it to other code generators. Aside from the explanation that it is a fork of `recast` there's no mention of prior art.

I didn't intend to, but I realize I'm being harsh and that is not what I intended. I'm just irritable today because I just inherited the PHP '90s codebase from hell and need a solution that reformats everything (HTML, CSS, JS, PHP, Apache) yesterday. That's beside the point. I think `prettier` is great ❤️ , and especially the community that's developing around it focussed on making code beautiful and readable again, and would encourage you to continue regardless of any prior art.

**Comment by wmhilton** [comment]
Having now tried to use `esprima` + `escodegen` for my project (thinking they might be more mature) I can list some other differences now:

**esprima / escodegen discard comments by default**. There's supposed to be a way to preserve comments, but after 3 tries I still couldn't get it. *prettier worked on my first try, with no "gotcha!" surprises.*

**esprima / escodegen are separate projects by separate people** [esprima](https://github.com/jquery/esprima) is in the `jquery` Github org, while [escodegen](https://github.com/estools/escodegen) is part of the `estools` Github org. Their APIs feel similar, but they are written and maintained by different people. (The primary author of `esprima` has only made 3 commits to `escodegen`!) It's not hard to imagine the projects getting out of sync, with `esprima` capable of parsing more types of syntax than `escodegen` can handle generating. (Which may have already happened for all I know.)

**Comment by jlongster** [comment]
Yeah, there are going to be a ton of little differences. Everything from comments, to flow, to JSX... We do a lot of things, and how we wrap code to fit into a maximum line length is crucial for this actually working on real-world codebases, and is much different than most others.
