### ISSUE TITLE
Flow declarations lose their `declaration` keyword

### ISSUE THREAD

**Issue by tmcw** [jlongster/prettier#659]
prettier transforms a [Flow declaration](https://flowtype.org/docs/declarations.html) like

```js
declare type Foo = string;
```

into

```js
type Foo = string;
```

Here's [that in the web UI](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22declare%20type%20Foo%20%3D%20string%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D).

Are flow declarations in scope for prettier or are they not considered proper JavaScript?

**Comment by vjeux** [comment]
`declare type X` and `type X` are equivalent with flow. Unfortunately, the flow parser (unlike babylon) produces the same AST for both with no way of determining which one it is. The heuristic we used is that if you are inside of a `declare module` block then we put `declare` everywhere otherwise we don't.

We should probably get the flow team to provide a way to dissociate the two and in the meantime look at the file content to determine whether it has declare or not.
 
```js
declare module X {
  declare type Foo = string;
}
```

> Are flow declarations in scope for prettier or are they not considered proper JavaScript?

Absolutely in scope. Please send bug reports :)
