### ISSUE TITLE
Respect line breaks in object literals

### ISSUE THREAD

**Issue by sporto** [jlongster/prettier#66]
We format our object literals like:

```
var record = {
  cat: 3,
  lion,
  monkey: 1,
}
```

Prettier changes this to (depending on the width setting).

```
var record = { cat: 3, lion, monkey: 1 };
```

But we would like to always have the formatting above. We do this because:

- It is easier to scan
- It is easier to remove a value by just deleting a line
- It is easier to sort 
- It creates cleaner PRs (when a line is deleted or added)

So an option for this would be great, thanks.

**Comment by jlongster** [comment]
We're not going to do this, because collapsing is a pretty critical part of the printer. If the object doesn't fit on a line, it's pretty small and easy to deal with anyway. And PRs, on github at least, highlight the exact text on the line that was added or removed.

Since collapsing objects are a core part of this printer, I'm closing this. There are too many formats that are cleaned up by collapsing small objects (when they are passed to function, etc).
