### ISSUE TITLE
Unneeded parenthesis around !await x()

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#728]
```js
async function f() {
  a = !await f();
}
```

outputs

```js
async function f() {
  a = !(await f());
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22async%20function%20f()%20%7B%5Cn%20%20a%20%3D%20!await%20f()%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by bakkot** [comment]
Personally I kind of like those parentheses, even if they aren't necessary.

**Comment by bakkot** [comment]
Though either way it should be consistent with other keyword unary operations, which [it's not](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22!(typeof%20f)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D).

```js
!typeof a;
!delete a.b;
!void a;
```
do not (currently) have parentheses (since they don't need them).

On the other hand, the parentheses are necessary in 
```js
function *f(){
  !(yield a);
}
```
because `YieldExpression` [is an](https://tc39.github.io/ecma262/#sec-assignment-operators) `AssignmentExpression`, not a `UnaryExpression`.

(Yes, this is kind of an inconsistency in the spec.)

I'd personally be happier if all of those got parentheses.

**Comment by vjeux** [comment]
Thanks for the information! Right now our stance with prettier is to only put parenthesis when needed to make it valid. Could you open another issue for this so that we can discuss it? Thanks!
