### ISSUE TITLE
Trailing Comma Arg in CLI Being Ignored

### ISSUE THREAD

**Issue by jonlabelle** [jlongster/prettier#747]
It seems the `--trailing-comma` CLI arg is not adhering to `none`; and only working (no trailing comma) when set to `false`.

![trailing-comma-ss](https://cloud.githubusercontent.com/assets/226837/23126964/bec6a1c4-f73e-11e6-8889-366c83dfcdbe.png)

**Comment by jlongster** [comment]
Sorry, this is because the docs are talking about the master branch, and 0.18.0 does not have the updated trailing comma options. This is unfortunate, and I will add a note to the docs about the difference in versions.

We haven't released a version yet that includes the updated option, but will very soon. Until then you could install it straight from github.

**Comment by jlongster** [comment]
I added a note in the README about this. We'll release 0.19.0 probably today.

**Comment by jonlabelle** [comment]
Thanks for the clarification @jlongster!
