### ISSUE TITLE
Spaces inside JSX curly braces are removed

### ISSUE THREAD

**Issue by antoinerey** [jlongster/prettier#95]
I use to write my JSX like this

```jsx
<div className={ className }>
  Bla bla bla
</div>
```
Note the spaces inside the `className` curly braces.

But it's formatted like this

```jsx
<div className={className}>
  Bla bla bla
</div>
```

I find reading this with spaces easier. So, would that be possible to keep spaces if there are any ?

**Comment by suchipi** [comment]
Is discussion about personal preference valuable? Just feels like bikeshedding.

The airbnb style guide prefers no spaces: https://github.com/airbnb/javascript/tree/master/react#spacing
The shopify style guide prefers no spaces:
https://github.com/Shopify/javascript/tree/master/react#2.3
The react docs don't use spaces:
https://facebook.github.io/react/docs/conditional-rendering.html

I feel like I see no spaces more commonly in community code than the reverse.

**Comment by jlongster** [comment]
Yeah, for questions like this, we go with what we feel the majority of users expect. As noted in several other places, particularly https://github.com/jlongster/prettier/issues/40, this project is not aiming for people who want granular control over everything, because we believe it really doesn't matter. Whenever I find that I prefer one style but am forced to use another, within weeks I prefer the other style because that's what my brain is used to seeing. This is all subjective and we want to build a tool that helps people converge on a single(-ish) style that just works. (The "ish" is because we do have a few basic options)

**Comment by milewski** [comment]
@suchipi all the example you posted dont use space, but i have a strong feeling that this one does recommend: https://vuejs.org/v2/style-guide/#Quoted-attribute-values-strongly-recommended , i'm just writing my first app using jsx and this syntax `className={className}` is starting to hurt my eyes.... any change of at least having an option to enable it?
